site_name: Shop 6 in 1

# Repository
repo_name: 'Shop Kotlin Multiplatform'
repo_url: 'https://github.com/keygenqt/km-shop'

# Navigation
nav:
  - 'Overview': index.md
  - 'Website':
      - 'About': frontend/index.md
  - 'Admin Panel':
      - 'About': backend/index.md
  - 'iOS':
      - 'About': ios/index.md
  - 'Android':
      - 'About': android/index.md
      - 'Dokka': dokka/shop/mobile/android/index.html
  - 'API':
      - 'About': api/index.md
      - 'Methods':
          - 'Greeting': api/demo/greeting.md
          - 'Rockets': api/demo/rockets.md
      - 'Dokka': dokka/shop/server/api/index.html
  - 'Server CLI':
      - 'About': cli/index.md
      - 'Dokka': dokka/shop/server/cli/index.html
  - 'Package Shared':
      - 'About': shared/index.md
      - 'Dokka': dokka/shared/index.html

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'black'
    accent: 'deep orange'
  font:
    text: 'Roboto'
    code: 'JetBrains Mono'