##########################
## VERSIONS
##########################

[versions]
# https://insert-koin.io/docs/setup/koin#ktor
koinKtorVersion="3.2.2"
# https://github.com/ktorio/ktor/releases
ktorVersion = "2.1.3"
# https://mvnrepository.com/artifact/ch.qos.logback/logback-classic
logbackVersion = "1.4.4"
## https://github.com/Kotlin/kotlinx.serialization/blob/master/formats/README.md#json
jsonSerializationVersion="1.4.1"

##########################
## LIBRARIES
##########################

# Serialization
# JSON serialization library dependency
[libraries.kotlinx-serialization-json]
module = "org.jetbrains.kotlinx:kotlinx-serialization-json"
[libraries.kotlinx-serialization-json.version]
ref = "jsonSerializationVersion"

# Koin
# Koin is a smart Kotlin dependency injection library to keep you focused on your app, not on your tools
[libraries.koin-ktor]
module = "io.insert-koin:koin-ktor"
[libraries.koin-ktor.version]
ref = "koinKtorVersion"

# Ktor
# Create asynchronous client and server applications. Anything from microservices to multiplatform HTTP client apps in a simple way. Open Source, free, and fun!
[libraries.ktor-server-auth-jvm]
module = "io.ktor:ktor-server-auth-jvm"
[libraries.ktor-server-auth-jvm.version]
ref = "ktorVersion"

[libraries.ktor-server-core-jvm]
module = "io.ktor:ktor-server-core-jvm"
[libraries.ktor-server-core-jvm.version]
ref = "ktorVersion"

[libraries.ktor-server-sessions-jvm]
module = "io.ktor:ktor-server-sessions-jvm"
[libraries.ktor-server-sessions-jvm.version]
ref = "ktorVersion"

[libraries.ktor-server-netty-jvm]
module = "io.ktor:ktor-server-netty-jvm"
[libraries.ktor-server-netty-jvm.version]
ref = "ktorVersion"

[libraries.ktor-client-content-negotiation]
module = "io.ktor:ktor-server-content-negotiation"
[libraries.ktor-client-content-negotiation.version]
ref = "ktorVersion"

[libraries.ktor-server-html-builder]
module = "io.ktor:ktor-server-html-builder"
[libraries.ktor-server-html-builder.version]
ref = "ktorVersion"

[libraries.ktor-serialization-kotlinx-json-jvm]
module = "io.ktor:ktor-serialization-kotlinx-json-jvm"
[libraries.ktor-serialization-kotlinx-json-jvm.version]
ref = "ktorVersion"

[libraries.logback-classic]
module = "ch.qos.logback:logback-classic"
[libraries.logback-classic.version]
ref = "logbackVersion"

##########################
## BUNDLES
##########################

[bundles]
ktor = [
    "kotlinx-serialization-json",
    "koin-ktor",
    "ktor-server-auth-jvm",
    "ktor-server-core-jvm",
    "ktor-server-sessions-jvm",
    "ktor-server-netty-jvm",
    "ktor-client-content-negotiation",
    "ktor-serialization-kotlinx-json-jvm",
    "ktor-server-html-builder",
    "logback-classic",
]
