##########################
## VERSIONS
##########################

[versions]
# https://kotlinlang.org/docs/releases.html#release-details
kotlinVersion = "1.7.20"
# https://developer.android.com/jetpack/androidx/releases/compose
composeVersion = "1.3.0"
# https://developer.android.com/jetpack/androidx/releases/activity
activityComposeVersion = "1.6.1"
# https://developer.android.com/jetpack/compose/navigation
navigationComposeVersion = "2.5.3"
# https://developer.android.com/jetpack/compose/libraries#hilt-navigation
hiltNavigationComposeVersion = "1.0.0"
# https://github.com/google/accompanist/releases
accompanistVersion = "0.28.0"
# https://developer.android.com/training/dependency-injection/hilt-android
hiltAndroidVersion = "2.44"
# https://github.com/Kotlin/kotlinx.serialization/blob/master/formats/README.md#json
jsonSerializationVersion="1.4.1"
# https://developer.android.com/jetpack/androidx/releases/room
roomVersion = "2.4.3"
# https://github.com/airbnb/lottie/blob/master/android-compose.md
lottieVersion = "5.2.0"

##########################
## LIBRARIES
##########################

# Lottie
# This repo is the home of the unified Lottie docs hosted at http://airbnb.io/lottie.
[libraries.lottie-compose]
module = "com.airbnb.android:lottie-compose"
[libraries.lottie-compose.version]
ref = "lottieVersion"

# Accompanist
# Accompanist is a group of libraries that aim to supplement Jetpack Compose with features that are commonly required by developers but not yet available.
[libraries.accompanist-pager]
module = "com.google.accompanist:accompanist-pager"
[libraries.accompanist-pager.version]
ref = "accompanistVersion"

[libraries.accompanist-swiperefresh]
module = "com.google.accompanist:accompanist-swiperefresh"
[libraries.accompanist-swiperefresh.version]
ref = "accompanistVersion"

# Reflection
# Reflection is a set of language and library features that allows you to introspect the structure of your program at runtime.
[libraries.kotlin-reflect]
module = "org.jetbrains.kotlin:kotlin-reflect"
[libraries.kotlin-reflect.version]
ref = "kotlinVersion"

# Hilt Android
[libraries.hilt-android]
module = "com.google.dagger:hilt-android"
[libraries.hilt-android.version]
ref = "hiltAndroidVersion"

[libraries.hilt-android-compiler]
module = "com.google.dagger:hilt-android-compiler"
[libraries.hilt-android-compiler.version]
ref = "hiltAndroidVersion"

# Hilt Compose
[libraries.hilt-navigation-compose]
module = "androidx.hilt:hilt-navigation-compose"
[libraries.hilt-navigation-compose.version]
ref = "hiltNavigationComposeVersion"

# Jetpack Compose
# Define your UI programmatically with composable functions that describe its shape and data dependencies.
[libraries.ui]
module = "androidx.compose.ui:ui"
[libraries.ui.version]
ref = "composeVersion"

[libraries.ui-tooling]
module = "androidx.compose.ui:ui-tooling"
[libraries.ui-tooling.version]
ref = "composeVersion"

[libraries.ui-tooling-preview]
module = "androidx.compose.ui:ui-tooling-preview"
[libraries.ui-tooling-preview.version]
ref = "composeVersion"

[libraries.foundation]
module = "androidx.compose.foundation:foundation"
[libraries.foundation.version]
ref = "composeVersion"

[libraries.material]
module = "androidx.compose.material:material"
[libraries.material.version]
ref = "composeVersion"

[libraries.material-icons-extended]
module = "androidx.compose.material:material-icons-extended"
[libraries.material-icons-extended.version]
ref = "composeVersion"

[libraries.activity-compose]
module = "androidx.activity:activity-compose"
[libraries.activity-compose.version]
ref = "activityComposeVersion"

[libraries.navigation-compose]
module = "androidx.navigation:navigation-compose"
[libraries.navigation-compose.version]
ref = "navigationComposeVersion"

# Serialization
# JSON serialization library dependency
[libraries.kotlinx-serialization-json]
module = "org.jetbrains.kotlinx:kotlinx-serialization-json"
[libraries.kotlinx-serialization-json.version]
ref = "jsonSerializationVersion"

# Room
# The Room persistence library provides an abstraction layer over SQLite to allow for more robust database access while harnessing the full power of SQLite.
[libraries.room-runtime]
module = "androidx.room:room-runtime"
[libraries.room-runtime.version]
ref = "roomVersion"

[libraries.room-ktx]
module = "androidx.room:room-ktx"
[libraries.room-ktx.version]
ref = "roomVersion"

[libraries.room-paging]
module = "androidx.room:room-paging"
[libraries.room-paging.version]
ref = "roomVersion"

[libraries.room-compiler]
module = "androidx.room:room-compiler"
[libraries.room-compiler.version]
ref = "roomVersion"

##########################
## BUNDLES
##########################

[bundles]
android = [
    "ui",
    "ui-tooling",
    "ui-tooling-preview",
    "foundation",
    "material",
    "material-icons-extended",
    "activity-compose",
    "navigation-compose",
    "kotlin-reflect",
    "hilt-android",
    "hilt-navigation-compose",
    "kotlinx-serialization-json",
    "accompanist-pager",
    "accompanist-swiperefresh",
    "room-runtime",
    "room-ktx",
    "room-paging",
    "lottie-compose",
]
androidKapt = [
    "hilt-android-compiler",
    "room-compiler"
]
