##########################
## VERSIONS
##########################

[versions]
## https://insert-koin.io/docs/setup/koin
koinVersion="3.2.2"
# https://github.com/ktorio/ktor/releases
ktorVersion = "2.1.3"
# https://mvnrepository.com/artifact/ch.qos.logback/logback-classic
logbackVersion = "1.4.4"
## https://mvnrepository.com/artifact/com.mysql/mysql-connector-j
mysqlConnectorVersion="8.0.31"
## https://flywaydb.org/documentation/learnmore/releaseNotes
flywayVersion="9.1.3"
## https://github.com/brettwooldridge/HikariCP/tags
hikariCpVersion="5.0.1"
## https://github.com/JetBrains/Exposed/releases
exposedVersion="0.39.2"
## https://github.com/Kotlin/kotlinx.serialization/blob/master/formats/README.md#json
jsonSerializationVersion="1.4.1"

##########################
## LIBRARIES
##########################

# Serialization
# JSON serialization library dependency
[libraries.kotlinx-serialization-json]
module = "org.jetbrains.kotlinx:kotlinx-serialization-json"
[libraries.kotlinx-serialization-json.version]
ref = "jsonSerializationVersion"

# Koin
# Koin is a smart Kotlin dependency injection library to keep you focused on your app, not on your tools
[libraries.koin-ktor]
module = "io.insert-koin:koin-ktor"
[libraries.koin-ktor.version]
ref = "koinVersion"

# MySQL Connector/J
# JDBC Type 4 driver for MySQL.
[libraries.mysql-connector-java]
module = "mysql:mysql-connector-java"
[libraries.mysql-connector-java.version]
ref = "mysqlConnectorVersion"

# HikariCP
# HikariCP is a "zero-overhead" production ready JDBC connection pool.
[libraries.hikari]
module = "com.zaxxer:HikariCP"
[libraries.hikari.version]
ref = "hikariCpVersion"

# Exposed
# ORM framework for Kotlin.
[libraries.exposed-core]
module = "org.jetbrains.exposed:exposed-core"
[libraries.exposed-core.version]
ref = "exposedVersion"

[libraries.exposed-dao]
module = "org.jetbrains.exposed:exposed-dao"
[libraries.exposed-dao.version]
ref = "exposedVersion"

[libraries.exposed-jdbc]
module = "org.jetbrains.exposed:exposed-jdbc"
[libraries.exposed-jdbc.version]
ref = "exposedVersion"

# Flyway
# Increase reliability of deployments by versioning your database
[libraries.flyway-core]
module = "org.flywaydb:flyway-core"
[libraries.flyway-core.version]
ref = "flywayVersion"

[libraries.flyway-mysql]
module = "org.flywaydb:flyway-mysql"
[libraries.flyway-mysql.version]
ref = "flywayVersion"

# Ktor
# Create asynchronous client and server applications. Anything from microservices to multiplatform HTTP client apps in a simple way. Open Source, free, and fun!
[libraries.ktor-server-auth-jvm]
module = "io.ktor:ktor-server-auth-jvm"
[libraries.ktor-server-auth-jvm.version]
ref = "ktorVersion"

[libraries.ktor-server-core-jvm]
module = "io.ktor:ktor-server-core-jvm"
[libraries.ktor-server-core-jvm.version]
ref = "ktorVersion"

[libraries.ktor-server-sessions-jvm]
module = "io.ktor:ktor-server-sessions-jvm"
[libraries.ktor-server-sessions-jvm.version]
ref = "ktorVersion"

[libraries.ktor-server-netty-jvm]
module = "io.ktor:ktor-server-netty-jvm"
[libraries.ktor-server-netty-jvm.version]
ref = "ktorVersion"

[libraries.ktor-client-content-negotiation]
module = "io.ktor:ktor-server-content-negotiation"
[libraries.ktor-client-content-negotiation.version]
ref = "ktorVersion"

[libraries.ktor-server-html-builder]
module = "io.ktor:ktor-server-html-builder"
[libraries.ktor-server-html-builder.version]
ref = "ktorVersion"

[libraries.ktor-serialization-kotlinx-json-jvm]
module = "io.ktor:ktor-serialization-kotlinx-json-jvm"
[libraries.ktor-serialization-kotlinx-json-jvm.version]
ref = "ktorVersion"

[libraries.logback-classic]
module = "ch.qos.logback:logback-classic"
[libraries.logback-classic.version]
ref = "logbackVersion"

##########################
## BUNDLES
##########################

[bundles]
ktor = [
    "kotlinx-serialization-json",
    "koin-ktor",
    "mysql-connector-java",
    "hikari",
    "exposed-core",
    "exposed-dao",
    "exposed-jdbc",
    "flyway-core",
    "flyway-mysql",
    "ktor-server-auth-jvm",
    "ktor-server-core-jvm",
    "ktor-server-sessions-jvm",
    "ktor-server-netty-jvm",
    "ktor-client-content-negotiation",
    "ktor-serialization-kotlinx-json-jvm",
    "ktor-server-html-builder",
    "logback-classic",
]
