##########################
## VERSIONS
##########################

[versions]
# kotlinx-cli
# https://github.com/Kotlin/kotlinx-cli
kotlinxCLIVersion = "0.3.5"

##########################
## LIBRARIES
##########################

# kotlinx-datetime
# A multiplatform Kotlin library for working with date and time.
[libraries.kotlinx-cli]
module = "org.jetbrains.kotlinx:kotlinx-cli"
[libraries.kotlinx-cli.version]
ref = "kotlinxCLIVersion"

##########################
## BUNDLES
##########################

[bundles]
cli = [
    "kotlinx-cli",
]
