##########################
## VERSIONS
##########################

[versions]
# https://insert-koin.io/docs/setup/koin#core
koinVersion="3.2.2"
# https://github.com/Kotlin/kotlinx-cli
kotlinxCLIVersion = "0.3.5"
# https://github.com/Kotlin/kotlinx.coroutines/blob/master/README.md
coroutinesVersion = "1.6.4"
# https://mvnrepository.com/artifact/org.slf4j
slf4jVersion = "2.0.3"
# https://github.com/lightbend/config
configVersion = "1.4.2"
# https://github.com/JetBrains/Exposed/releases
exposedVersion="0.39.2"
# https://mvnrepository.com/artifact/ch.qos.logback/logback-classic
logbackVersion = "1.4.4"

##########################
## LIBRARIES
##########################

# Exposed
# ORM framework for Kotlin.
[libraries.exposed-core]
module = "org.jetbrains.exposed:exposed-core"
[libraries.exposed-core.version]
ref = "exposedVersion"

[libraries.exposed-dao]
module = "org.jetbrains.exposed:exposed-dao"
[libraries.exposed-dao.version]
ref = "exposedVersion"

# HOCON Config
# Configuration library for JVM languages.
[libraries.config]
module = "com.typesafe:config"
[libraries.config.version]
ref = "configVersion"

# Koin
# Koin is a smart Kotlin dependency injection library to keep you focused on your app, not on your tools
[libraries.koin-core]
module = "io.insert-koin:koin-core"
[libraries.koin-core.version]
ref = "koinVersion"

# kotlinx-datetime
# A multiplatform Kotlin library for working with date and time.
[libraries.kotlinx-cli]
module = "org.jetbrains.kotlinx:kotlinx-cli"
[libraries.kotlinx-cli.version]
ref = "kotlinxCLIVersion"

# kotlinx-coroutines
# Library support for Kotlin coroutines with multiplatform support.
[libraries.kotlinx-coroutines-core]
module = "org.jetbrains.kotlinx:kotlinx-coroutines-core"
[libraries.kotlinx-coroutines-core.version]
ref = "coroutinesVersion"

# Logback Project
# Logback is intended as a successor to the popular log4j project, picking up where log4j 1.x leaves off.
[libraries.logback-classic]
module = "ch.qos.logback:logback-classic"
[libraries.logback-classic.version]
ref = "logbackVersion"

##########################
## BUNDLES
##########################

[bundles]
cli = [
    "exposed-core",
    "exposed-dao",
    "config",
    "koin-core",
    "kotlinx-cli",
    "kotlinx-coroutines-core",
    "logback-classic",
]
