##########################
## VERSIONS
##########################

[versions]
# https://insert-koin.io/docs/setup/koin#core
koinVersion="3.2.2"
# https://github.com/Kotlin/kotlinx-cli
kotlinxCLIVersion = "0.3.5"
# https://github.com/Kotlin/kotlinx.coroutines/blob/master/README.md
coroutinesVersion = "1.6.4"
# https://mvnrepository.com/artifact/org.slf4j
slf4jVersion = "2.0.3"
# https://github.com/lightbend/config
configVersion = "1.4.2"

##########################
## LIBRARIES
##########################

# HOCON Config
# Configuration library for JVM languages.
[libraries.config]
module = "com.typesafe:config"
[libraries.config.version]
ref = "configVersion"

# Koin
# Koin is a smart Kotlin dependency injection library to keep you focused on your app, not on your tools
[libraries.koin-core]
module = "io.insert-koin:koin-core"
[libraries.koin-core.version]
ref = "koinVersion"

# kotlinx-datetime
# A multiplatform Kotlin library for working with date and time.
[libraries.kotlinx-cli]
module = "org.jetbrains.kotlinx:kotlinx-cli"
[libraries.kotlinx-cli.version]
ref = "kotlinxCLIVersion"

# kotlinx-coroutines
# Library support for Kotlin coroutines with multiplatform support.
[libraries.kotlinx-coroutines-core]
module = "org.jetbrains.kotlinx:kotlinx-coroutines-core"
[libraries.kotlinx-coroutines-core.version]
ref = "coroutinesVersion"

# slf4j
# The Simple Logging Facade for Java
[libraries.slf4j-api]
module = "org.slf4j:slf4j-api"
[libraries.slf4j-api.version]
ref = "slf4jVersion"

[libraries.slf4j-simple]
module = "org.slf4j:slf4j-simple"
[libraries.slf4j-simple.version]
ref = "slf4jVersion"

##########################
## BUNDLES
##########################

[bundles]
cli = [
    "config",
    "koin-core",
    "kotlinx-cli",
    "slf4j-api",
    "slf4j-simple",
    "kotlinx-coroutines-core",
]
