##########################
## VERSIONS
##########################

[versions]
# https://developer.android.com/jetpack/androidx/releases/compose
composeVersion = "1.3.0"
# https://developer.android.com/jetpack/androidx/releases/activity
activityComposeVersion = "1.6.1"
# https://developer.android.com/training/dependency-injection/hilt-android
hiltVersion = "2.44"

##########################
## LIBRARIES
##########################

# Hilt
# Hilt is a dependency injection library for Android that reduces the boilerplate of doing manual dependency injection in your project.
[libraries.hilt-android]
module = "com.google.dagger:hilt-android"
[libraries.hilt-android.version]
ref = "hiltVersion"

[libraries.hilt-android-compiler]
module = "com.google.dagger:hilt-android-compiler"
[libraries.hilt-android-compiler.version]
ref = "hiltVersion"

# Jetpack Compose
# Define your UI programmatically with composable functions that describe its shape and data dependencies.
[libraries.ui]
module = "androidx.compose.ui:ui"
[libraries.ui.version]
ref = "composeVersion"

[libraries.ui-tooling]
module = "androidx.compose.ui:ui-tooling"
[libraries.ui-tooling.version]
ref = "composeVersion"

[libraries.ui-tooling-preview]
module = "androidx.compose.ui:ui-tooling-preview"
[libraries.ui-tooling-preview.version]
ref = "composeVersion"

[libraries.foundation]
module = "androidx.compose.foundation:foundation"
[libraries.foundation.version]
ref = "composeVersion"

[libraries.material]
module = "androidx.compose.material:material"
[libraries.material.version]
ref = "composeVersion"

[libraries.activity-compose]
module = "androidx.activity:activity-compose"
[libraries.activity-compose.version]
ref = "activityComposeVersion"

##########################
## BUNDLES
##########################

[bundles]
android = [
    "ui",
    "ui-tooling",
    "ui-tooling-preview",
    "foundation",
    "material",
    "activity-compose",
    "hilt-android",
]
androidKapt = [
    "hilt-android-compiler",
]
